// 休憩スポットのサンプルデータ(道の駅・SA/PA) - Google Maps API で検証済み座標
export const spots = [
  {
    name: '道の駅 川場田園プラザ',
    address: '群馬県利根郡川場村萩室385',
    lat: 36.6864905,
    lng: 139.1079444,
    region: 'kanto',
    facilities: {
      shower: false,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00(施設により異なる)',
  },
  {
    name: '海老名サービスエリア(下り線)',
    address: '〒243-0411 神奈川県海老名市大谷南5-2-1',
    lat: 35.4302425,
    lng: 139.4008624,
    region: 'kanto',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '足柄サービスエリア(上り線)',
    address: '〒412-0023 静岡県御殿場市深沢字前沢1801-1',
    lat: 35.31291849999999,
    lng: 138.9566778,
    region: 'kanto',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '谷田部東パーキングエリア(上り線)',
    address: '茨城県つくば市下原263-2',
    lat: 36.0381601,
    lng: 140.1384472,
    region: 'kanto',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: false,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業(売店は6:00〜22:00)',
  },
  {
    name: '道の駅 ましこ',
    address: '〒321-4225 栃木県芳賀郡益子町長堤2271',
    lat: 36.4312358,
    lng: 140.0723528,
    region: 'kanto',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00',
  },
  {
    name: '三木サービスエリア(上り線)',
    address: '兵庫県三木市福井2596',
    lat: 34.7948447,
    lng: 134.977855,
    region: 'kinki',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 みやま',
    address: '〒835-0019 福岡県みやま市瀬高町大江2328',
    lat: 33.1474122,
    lng: 130.4838916,
    region: 'kyushu',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: true,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜19:00',
  },
  {
    name: '桂川パーキングエリア(下り線)',
    address: '京都府京都市南区久世東土川町',
    lat: 34.9458062,
    lng: 135.720125,
    region: 'kyushu',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 きつれがわ',
    address: '〒329-1412 栃木県さくら市喜連川4145-10',
    lat: 36.7153737,
    lng: 140.0329636,
    region: 'kanto',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: true,
      laundry: true,
      open24h: false,
    },
    hours: '9:00〜19:00',
  },
  {
    name: '双葉サービスエリア(上り線)',
    address: '〒400-0104 山梨県甲斐市龍地2630',
    lat: 35.6797546,
    lng: 138.5101039,
    region: 'tohoku',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 とうや湖',
    address: '北海道虻田郡洞爺湖町香川9-4',
    lat: 42.6644903,
    lng: 140.8220166,
    region: 'hokkaido',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00',
  },
  {
    name: '輪厚パーキングエリア(札幌方面)',
    address: '〒061-1264 北海道北広島市輪厚531-6',
    lat: 42.9524968,
    lng: 141.5128428,
    region: 'hokkaido',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '安達太良サービスエリア(上り線)',
    address: '〒969-1158 福島県本宮市本宮天ヶ221',
    lat: 37.5152799,
    lng: 140.3825677,
    region: 'tohoku',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '駒ヶ岳サービスエリア(上り線)',
    address: '長野県駒ヶ根市赤穂',
    lat: 35.7322171,
    lng: 137.9182351,
    region: 'chubu',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 富士川楽座',
    address: '静岡県富士市岩淵1488-1',
    lat: 35.1618707,
    lng: 138.618454,
    region: 'chubu',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜21:00',
  },
  {
    name: '草津パーキングエリア(上り線)',
    address: '滋賀県草津市岡本町',
    lat: 34.9931553,
    lng: 135.9777044,
    region: 'kinki',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 針T.R.S',
    address: '奈良県奈良市針町345',
    lat: 34.6102101,
    lng: 135.9632352,
    region: 'kinki',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業(売店は7:00〜21:00)',
  },
  {
    name: '七塚原サービスエリア(下り線)',
    address: '〒727-0011 広島県庄原市東本町',
    lat: 34.8609918,
    lng: 133.0219188,
    region: 'chugoku',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 北の関宿安芸高田',
    address: '広島県安芸高田市美土里町横田331-1',
    lat: 34.7212725,
    lng: 132.6808307,
    region: 'chugoku',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00',
  },
  {
    name: '豊浜サービスエリア(松山方面)',
    address: '〒769-1604 香川県観音寺市豊浜町箕浦甲1842-2',
    lat: 34.0533733,
    lng: 133.6342981,
    region: 'shikoku',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '北熊本サービスエリア(下り線)',
    address: '〒861-5515 熊本県熊本市北区改寄町1563',
    lat: 32.8943709,
    lng: 130.7200802,
    region: 'kyushu',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
];
