// 休憩スポットのサンプルデータ(道の駅・SA/PA)
export const spots = [
  {
    name: '道の駅 川場田園プラザ',
    address: '群馬県利根郡川場村萩室385',
    lat: 36.6469,
    lng: 139.1257,
    region: 'kanto',
    facilities: {
      shower: false,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00(施設により異なる)',
  },
  {
    name: '海老名サービスエリア(下り線)',
    address: '神奈川県海老名市河原口2863',
    lat: 35.4427,
    lng: 139.3920,
    region: 'kanto',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '足柄サービスエリア(上り線)',
    address: '神奈川県南足柄市矢倉沢2557',
    lat: 35.3245,
    lng: 139.0451,
    region: 'kanto',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '谷田部東パーキングエリア(上り線)',
    address: '茨城県つくば市下原263-2',
    lat: 36.038517,
    lng: 140.138206,
    region: 'kanto',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: false,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業(売店は6:00〜22:00)',
  },
  {
    name: '道の駅 ましこ',
    address: '栃木県芳賀郡益子町山本3527',
    lat: 36.4564,
    lng: 140.0991,
    region: 'kanto',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00',
  },
  {
    name: '三木サービスエリア(上り線)',
    address: '兵庫県三木市福井2596',
    lat: 34.8197,
    lng: 135.0203,
    region: 'kinki',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 みやま',
    address: '福岡県みやま市瀬高町小川933',
    lat: 33.1325,
    lng: 130.4769,
    region: 'kyushu',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: true,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜19:00',
  },
  {
    name: '桂川パーキングエリア(下り線)',
    address: '福岡県嘉穂郡桂川町土居2640',
    lat: 33.5853,
    lng: 130.6473,
    region: 'kyushu',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 きつれがわ',
    address: '栃木県さくら市卯の里1-1-1',
    lat: 36.7156,
    lng: 140.0166,
    region: 'kanto',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: true,
      laundry: true,
      open24h: false,
    },
    hours: '9:00〜19:00',
  },
  {
    name: '双葉サービスエリア(上り線)',
    address: '福島県双葉郡浪江町大字幾世橋',
    lat: 37.4858,
    lng: 140.9893,
    region: 'tohoku',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 とうや湖',
    address: '北海道虻田郡洞爺湖町香川9-4',
    lat: 42.664726,
    lng: 140.822164,
    region: 'hokkaido',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00',
  },
  {
    name: '輪厚パーキングエリア(札幌方面)',
    address: '北海道北広島市輪厚817',
    lat: 42.9333,
    lng: 141.5500,
    region: 'hokkaido',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '安達太良サービスエリア(上り線)',
    address: '福島県本宮市切山字蛇穴沢',
    lat: 37.5167,
    lng: 140.4167,
    region: 'tohoku',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '駒ヶ岳サービスエリア(上り線)',
    address: '長野県駒ヶ根市赤穂',
    lat: 35.7333,
    lng: 137.9333,
    region: 'chubu',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 富士川楽座',
    address: '静岡県富士市岩淵1488-1',
    lat: 35.161880,
    lng: 138.618457,
    region: 'chubu',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜21:00',
  },
  {
    name: '草津パーキングエリア(上り線)',
    address: '滋賀県草津市岡本町',
    lat: 35.0167,
    lng: 135.9667,
    region: 'kinki',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 針T.R.S',
    address: '奈良県奈良市針町345',
    lat: 34.610207,
    lng: 135.962355,
    region: 'kinki',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業(売店は7:00〜21:00)',
  },
  {
    name: '七塚原サービスエリア(下り線)',
    address: '広島県庄原市七塚町',
    lat: 34.8500,
    lng: 133.0167,
    region: 'chugoku',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '道の駅 北の関宿安芸高田',
    address: '広島県安芸高田市美土里町横田331-1',
    lat: 34.721488,
    lng: 132.680960,
    region: 'chugoku',
    facilities: {
      shower: false,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: false,
    },
    hours: '9:00〜18:00',
  },
  {
    name: '豊浜サービスエリア(松山方面)',
    address: '香川県観音寺市豊浜町箕浦2180-1',
    lat: 34.056951,
    lng: 133.637171,
    region: 'shikoku',
    facilities: {
      shower: true,
      sleepingArea: false,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
  {
    name: '北熊本サービスエリア(下り線)',
    address: '熊本県合志市御代志',
    lat: 32.8833,
    lng: 130.7333,
    region: 'kyushu',
    facilities: {
      shower: true,
      sleepingArea: true,
      largeParking: true,
      restaurant: true,
      onsen: false,
      laundry: false,
      open24h: true,
    },
    hours: '24時間営業',
  },
];
